// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Subasta.Infraestructura.Persistencia;

#nullable disable

namespace Subasta.Infraestructura.Migrations
{
    [DbContext(typeof(App_DB_Context))]
    [Migration("20250708043247_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Subasta_Dominio.Entidades.Subastas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estado_Subasta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Estado");

                    b.Property<DateTime?>("Fecha_Fin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha_Fin");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha_Inicio");

                    b.Property<string>("Id_Dueño_Subasta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Id_Dueño");

                    b.Property<string>("Id_Ganador")
                        .HasColumnType("text")
                        .HasColumnName("Id_Postor_Ganador");

                    b.Property<string>("Id_Producto_Asociado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Id_Producto");

                    b.Property<decimal>("Incremento_Minimo")
                        .HasColumnType("numeric")
                        .HasColumnName("Incremento_Minimo");

                    b.Property<string>("Nombre_Subasta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<decimal>("Precio_Cierre_Automatico")
                        .HasColumnType("numeric")
                        .HasColumnName("Precio_Cierre_Automatico");

                    b.Property<decimal?>("Precio_Final")
                        .HasColumnType("numeric")
                        .HasColumnName("Precio_Final");

                    b.Property<decimal>("Precio_Inicial")
                        .HasColumnType("numeric")
                        .HasColumnName("Precio_Inicial");

                    b.Property<decimal>("Precio_Reserva")
                        .HasColumnType("numeric")
                        .HasColumnName("Precio_Reserva");

                    b.HasKey("Id");

                    b.ToTable("Subasta", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
